"""
src/tools/mock_api.py
Mock e-commerce API for Zeladija.
Loads orders from data/raw/orders.json (generated by scripts/generate_orders.py).
Wraps lookup functions as LangChain tools using the @tool decorator.
"""

import json
import os
from pathlib import Path
from loguru import logger
from dotenv import load_dotenv
from langchain_core.tools import tool

load_dotenv()

ORDERS_JSON_PATH = os.getenv("ORDERS_JSON_PATH", "./data/raw/orders.json")

# Load order data at import time to simulate a persistent database for the mock API
def _load_orders() -> tuple[dict, dict]:
    """Load orders.json and build lookup indexes."""
    path = Path(ORDERS_JSON_PATH)
    if not path.exists():
        logger.warning(
            f"orders.json not found at {path}. "
            "Run: python scripts/generate_orders.py"
        )
        return {}, {}

    with open(path) as f:
        orders_list = json.load(f)

    orders_by_id = {o["order_id"]: o for o in orders_list}
    orders_by_customer: dict[str, list[str]] = {}
    for o in orders_list:
        orders_by_customer.setdefault(o["customer_id"], []).append(o["order_id"])

    logger.info(
        f"Mock API loaded {len(orders_by_id)} orders "
        f"for {len(orders_by_customer)} customers from {path}"
    )
    return orders_by_id, orders_by_customer


ORDERS_BY_ID, ORDERS_BY_CUSTOMER = _load_orders()


# LangChain Tools 

@tool
def get_order_status(order_id: str) -> dict:
    """
    Fetch current status and full details for an order by its order ID.

    Returns a dict with: order_id, customer_id, status, order_date,
    estimated_delivery, carrier, tracking_url, items, total, shipping_address.
    Returns {'error': 'Order not found'} if the order_id is invalid.
    """
    order_id_clean = order_id.strip().upper()
    result = ORDERS_BY_ID.get(order_id_clean, {"error": "Order not found", "order_id": order_id_clean})
    logger.debug(f"[mock_api] get_order_status({order_id_clean}) → status={result.get('status', 'not_found')}")
    return result


@tool
def get_customer_orders(customer_id: str) -> list[str]:
    """
    Get all order IDs associated with a given customer ID.

    Returns a list of order ID strings (e.g. ['ORD-AB12CD34', 'ORD-XY98ZW01']).
    Returns an empty list if no orders are found for that customer.
    """
    customer_id_clean = customer_id.strip().upper()
    result = ORDERS_BY_CUSTOMER.get(customer_id_clean, [])
    logger.debug(f"[mock_api] get_customer_orders({customer_id_clean}) → {len(result)} orders")
    return result


@tool
def get_order_items(order_id: str) -> list[dict]:
    """
    Get the list of items in a specific order.

    Returns a list of dicts with: sku, name, qty, price.
    Returns [] if the order is not found.
    """
    order_id_clean = order_id.strip().upper()
    order = ORDERS_BY_ID.get(order_id_clean, {})
    return order.get("items", [])


# Helper functions (non-LangChain, for internal use) 

def get_orders_for_customer_full(customer_id: str) -> list[dict]:
    """Return full order dicts (not just IDs) for a given customer."""
    customer_id_clean = customer_id.strip().upper()
    order_ids = ORDERS_BY_CUSTOMER.get(customer_id_clean, [])
    return [ORDERS_BY_ID[oid] for oid in order_ids if oid in ORDERS_BY_ID]


def get_orders_by_status(status: str) -> list[dict]:
    """Return all orders with a specific status (for testing/eval)."""
    return [o for o in ORDERS_BY_ID.values() if o.get("status") == status]


def list_all_order_ids() -> list[str]:
    """Return all order IDs in the mock database (for eval test case generation)."""
    return list(ORDERS_BY_ID.keys())


def list_all_customer_ids() -> list[str]:
    """Return all customer IDs in the mock database."""
    return list(ORDERS_BY_CUSTOMER.keys())


# Tool registry (for passing to LangChain agents) 
ALL_TOOLS = [get_order_status, get_customer_orders, get_order_items]